language: python	
python:	
 - "2.7"	
cache: pip	
install:	
 - pip install -r requirements.txt
 - pip install coveralls
 - pip install codeclimate-test-reporter
script:	
 - nosetests tests --with-coverage
after_success:
 - coveralls
 - codeclimate-test-reporter
 