language: python	
python:	
 - "2.7"	
cache: pip	
install:	
 - pip install -r requirements.txt
 - pip install coveralls
 - pip install codeclimate-test-reporter
addons:
  postgresql: "10"
  apt:
    packages:
     - postgresql-10
     - postgresql-client-10
env:
  global:
   - PGPORT=5433
   - DATABASE_NAME = 'test_db'
   - DATABASE_USER = 'postgres'
   - DATABASE_PASSWORD = 'testme'
services:
 - postgresql
before_script:
 - psql -c "CREATE DATABASE test_db;" -U postgres
 - psql -c "CREATE USER postgres WITH PASSWORD 'testme';"
script:	
 - nosetests tests --with-coverage
after_success:
 - coveralls
 - codeclimate-test-reporter
 